export type PotionRarity =
    | "starter"
    | "common"
    | "uncommon"
    | "rare"
    | "special";

export type PotionCharacter =
    | "any"
    | "ironclad"
    | "silent"
    | "regent"
    | "necrobinder"
    | "defect";

export interface PotionDefinition{
    id: string;
    name: string;
    rarity: PotionRarity;
    character?: PotionCharacter;
    description: string
}

export const potions: PotionDefinition[] = [
    {
        id: "POTION.AMBERGRIS",
        name: "Ambergris",
        character: "any",
        description: "Heal for 50% of your max HP. If used in combat, take an extra turn.",
        rarity: "special",
    },
    {
        id: "POTION.ASHWATER",
        name: "Ashwater",
        character: "ironclad",
        description: "<span class=\"keyword-trigger inline-trigger\" data-name=\"Exhaust\" data-sequel=\"2\">[[Slay the Spire 2:Exhaust|Exhaust]]</span> any number of cards in your Hand.",
        rarity: "uncommon",
    },
    {
        id: "POTION.ATTACK_POTION",
        name: "Attack Potion",
        character: "any",
        description: "Choose 1 of 3 random Attack cards to add into your Hand. It's free to play this turn.",
        rarity: "common",
    },
    {
        id: "POTION.BEETLE_JUICE",
        name: "Beetle Juice",
        character: "any",
        description: "Enemy's attacks deal 30% less damage for the next 4 turns.",
        rarity: "rare",
    },
    {
        id: "POTION.BLESSING_OF_THE_FORGE",
        name: "Blessing of the Forge",
        character: "any",
        description: "<span class=\"keyword-trigger inline-trigger\" data-name=\"Upgrade\" data-sequel=\"2\">[[Slay the Spire 2:Upgrade|Upgrade]]</span> all cards in your Hand for the rest of combat.",
        rarity: "uncommon",
    },
    {
        id: "POTION.BLOCK_POTION",
        name: "Block Potion",
        character: "any",
        description: "Gain 12 <span class=\"keyword-trigger inline-trigger\" data-name=\"Block\" data-sequel=\"2\">[[File:StS2 Intent Defend.png|18px|link=Slay the Spire 2:Block]] [[Slay the Spire 2:Block|Block]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.BLOOD_POTION",
        name: "Blood Potion",
        character: "ironclad",
        description: "Heal for 20% of your Max HP.",
        rarity: "common",
    },
    {
        id: "POTION.BONE_BREW",
        name: "Bone Brew",
        character: "necrobinder",
        description: "<span class=\"keyword-trigger inline-trigger\" data-name=\"Summon\" data-sequel=\"2\">[[sts2:Osty#Summon|Summon]]</span> 15.",
        rarity: "uncommon",
    },
    {
        id: "POTION.BOTTLED_POTENTIAL",
        name: "Bottled Potential",
        character: "any",
        description: "Shuffle ALL your cards into your Draw Pile. Draw 5 cards.",
        rarity: "rare",
    },
    {
        id: "POTION.CLARITY",
        name: "Clarity Extract",
        character: "any",
        description: "Draw 1 card. At the start of your next 3 turns, draw 1 additional card.",
        rarity: "uncommon",
    },
    {
        id: "POTION.COLORLESS_POTION",
        name: "Colorless Potion",
        character: "any",
        description: "Choose 1 of 3 random Colorless cards to add into your Hand. It's free to play this turn.",
        rarity: "common",
    },
    {
        id: "POTION.COSMIC_CONCOCTION",
        name: "Cosmic Concoction",
        character: "regent",
        description: "Add 3 <span class=\"keyword-trigger inline-trigger\" data-name=\"Upgrade\" data-sequel=\"2\">[[Slay the Spire 2:Upgrade|Upgraded]]</span> Colorless cards into your Hand.",
        rarity: "rare",
    },
    {
        id: "POTION.CUNNING_POTION",
        name: "Cunning Potion",
        character: "silent",
        description: "Add 3 <span class=\"keyword-trigger inline-trigger\" data-name=\"Upgrade\" data-sequel=\"2\">[[Slay the Spire 2:Upgrade|Upgraded]]</span> <span class=\"card-trigger inline-trigger\" data-name=\"Shiv\" data-sequel=\"2\">[[File:StS2_CardIcon_Colorless_Attack_Token.png|24px|middle|link=Slay the Spire 2:Shiv]] [[Slay the Spire 2:Shiv|Shivs]]</span> into your Hand.",
        rarity: "uncommon",
    },
    {
        id: "POTION.CURE_ALL",
        name: "Cure All",
        character: "any",
        description: "Gain <span class='keyword-trigger' data-name='@CE' data-sequel='2'>[[File:StS2_EnergyColorless.png|20px|middle|link=]]</span>. Draw 2 cards.",
        rarity: "uncommon",
    },
    {
        id: "POTION.DEXTERITY_POTION",
        name: "Dexterity Potion",
        character: "any",
        description: "Gain 2 <span class=\"power-trigger inline-trigger\" data-name=\"Dexterity\" data-sequel=\"2\">[[File:StS2 Icon Dexterity.png|22px|link=Slay the Spire 2:Dexterity]] [[Slay the Spire 2:Dexterity|Dexterity]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.DISTILLED_CHAOS",
        name: "Distilled Chaos",
        character: "any",
        description: "Play the top 3 cards of your Draw Pile.",
        rarity: "rare",
    },
    {
        id: "POTION.DROPLET_OF_PRECOGNITION",
        name: "Droplet of Precognition",
        character: "any",
        description: "Choose a card in your Draw Pile and add it into your Hand.",
        rarity: "rare",
    },
    {
        id: "POTION.DUPLICATOR",
        name: "Duplicator",
        character: "any",
        description: "This turn, your next card is played an extra time.",
        rarity: "uncommon",
    },
    {
        id: "POTION.ENERGY_POTION",
        name: "Energy Potion",
        character: "any",
        description: "Gain <span class='keyword-trigger' data-name='@CE' data-sequel='2'>[[File:StS2_EnergyColorless.png|20px|middle|link=]]</span> <span class='keyword-trigger' data-name='@CE' data-sequel='2'>[[File:StS2_EnergyColorless.png|20px|middle|link=]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.ENTROPIC_BREW",
        name: "Entropic Brew",
        character: "any",
        description: "Fill all your empty potion slots with random potions.",
        rarity: "rare",
    },
    {
        id: "POTION.ESSENCE_OF_DARKNESS",
        name: "Essence of Darkness",
        character: "defect",
        description: "<span class=\"keyword-trigger inline-trigger\" data-name=\"Channel\" data-sequel=\"2\">[[Slay the Spire 2:Orbs|Channel]]</span> a <span class=\"keyword-trigger inline-trigger\" data-name=\"Dark\" data-sequel=\"2\">[[File:StS2 DarkOrb.png|18px|link=Slay the Spire 2:Dark]] [[Slay the Spire 2:Dark|Dark]]</span> for each of your Orb Slots.",
        rarity: "rare",
    },
    {
        id: "POTION.EXPLOSIVE_AMPOULE",
        name: "Explosive Ampoule",
        character: "any",
        description: "Deal 10 damage to ALL enemies.",
        rarity: "common",
    },
    {
        id: "POTION.FAIRY_IN_A_BOTTLE",
        name: "Fairy in a Bottle",
        character: "any",
        description: "When your HP would be reduced to 0, instead this potion is discarded and you heal to 30% of your Max HP.",
        rarity: "rare",
    },
    {
        id: "POTION.FIRE_POTION",
        name: "Fire Potion",
        character: "any",
        description: "Deal 20 damage.",
        rarity: "common",
    },
    {
        id: "POTION.FLEX_POTION",
        name: "Flex Potion",
        character: "any",
        description: "Gain 5 <span class=\"power-trigger inline-trigger\" data-name=\"Strength\" data-sequel=\"2\">[[File:StS2 Icon Strength.png|22px|link=Slay the Spire 2:Strength]] [[Slay the Spire 2:Strength|Strength]]</span>. At the end of your turn, lose 5 <span class=\"power-trigger inline-trigger\" data-name=\"Strength\" data-sequel=\"2\">[[File:StS2 Icon Strength.png|22px|link=Slay the Spire 2:Strength]] [[Slay the Spire 2:Strength|Strength]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.FOCUS_POTION",
        name: "Focus Potion",
        character: "defect",
        description: "Gain 2 <span class=\"power-trigger inline-trigger\" data-name=\"Focus\" data-sequel=\"2\">[[File:StS2 Icon Focus.png|22px|link=Slay the Spire 2:Orbs]] [[Slay the Spire 2:Orbs|Focus]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.FORTIFIER",
        name: "Fortifier",
        character: "any",
        description: "Triple your <span class=\"keyword-trigger inline-trigger\" data-name=\"Block\" data-sequel=\"2\">[[File:StS2 Intent Defend.png|18px|link=Slay the Spire 2:Block]] [[Slay the Spire 2:Block|Block]]</span>.",
        rarity: "uncommon",
    },
    {
        id: "POTION.FOUL_POTION",
        name: "Foul Potion",
        character: "any",
        description: "Deal 12 damage to EVERYONE.<br>Can be thrown at the Merchant for 100 Gold instead.",
        rarity: "special",
    },
    {
        id: "POTION.FRUIT_JUICE",
        name: "Fruit Juice",
        character: "any",
        description: "Gain 5 Max HP.",
        rarity: "rare",
    },
    {
        id: "POTION.FYSH_OIL",
        name: "Fysh Oil",
        character: "any",
        description: "Gain 1 <span class=\"power-trigger inline-trigger\" data-name=\"Strength\" data-sequel=\"2\">[[File:StS2 Icon Strength.png|22px|link=Slay the Spire 2:Strength]] [[Slay the Spire 2:Strength|Strength]]</span> and 1 <span class=\"power-trigger inline-trigger\" data-name=\"Dexterity\" data-sequel=\"2\">[[File:StS2 Icon Dexterity.png|22px|link=Slay the Spire 2:Dexterity]] [[Slay the Spire 2:Dexterity|Dexterity]]</span>.",
        rarity: "uncommon",
    },
    {
        id: "POTION.GAMBLERS_BREW",
        name: "Gambler's Brew",
        character: "any",
        description: "Discard any number of cards, then draw that many.",
        rarity: "uncommon",
    },
    {
        id: "POTION.GHOST_IN_A_JAR",
        name: "Ghost in a Jar",
        character: "silent",
        description: "Gain 1 <span class=\"power-trigger inline-trigger\" data-name=\"Intangible\" data-sequel=\"2\">[[File:StS2_Icon_Intangible.png|22px|link=Slay_the_Spire_2:Buffs#Intangible]] [[Slay_the_Spire_2:Buffs#Intangible|Intangible]]</span>.",
        rarity: "rare",
    },
    {
        id: "POTION.GIGANTIFICATION_POTION",
        name: "Gigantification Potion",
        character: "any",
        description: "The next Attack you play deals triple damage.",
        rarity: "rare",
    },
    {
        id: "POTION.GLOWWATER_POTION",
        name: "Glowwater Potion",
        character: "any",
        description: "<span class=\"keyword-trigger inline-trigger\" data-name=\"Exhaust\" data-sequel=\"2\">[[Slay the Spire 2:Exhaust|Exhaust]]</span> your Hand. Draw 10 cards.",
        rarity: "special",
    },
    {
        id: "POTION.HEART_OF_IRON",
        name: "Heart of Iron",
        character: "any",
        description: "Gain 7 <span class=\"power-trigger inline-trigger\" data-name=\"Plating\" data-sequel=\"2\">[[File:StS2_Icon_Plating.png|22px|link=Slay the Spire 2:Plating]] [[Slay the Spire 2:Plating|Plating]]</span>.",
        rarity: "uncommon",
    },
    {
        id: "POTION.KINGS_COURAGE",
        name: "King's Courage",
        character: "regent",
        description: "<span class=\"keyword-trigger inline-trigger\" data-name=\"Forge\" data-sequel=\"2\">[[Slay the Spire 2:Sovereign Blade|Forge]]</span> 15.",
        rarity: "uncommon",
    },
    {
        id: "POTION.LIQUID_BRONZE",
        name: "Liquid Bronze",
        character: "any",
        description: "Gain 3 <span class=\"power-trigger inline-trigger\" data-name=\"Thorns\" data-sequel=\"2\">[[File:StS2 Icon Thorns.png|22px|link=Slay the Spire 2:Thorns]] [[Slay the Spire 2:Thorns|Thorns]]</span>.",
        rarity: "uncommon",
    },
    {
        id: "POTION.LIQUID_MEMORIES",
        name: "Liquid Memories",
        character: "any",
        description: "Put a card from your Discard Pile into your Hand. It costs 0 <span class='keyword-trigger' data-name='@CE' data-sequel='2'>[[File:StS2_EnergyColorless.png|20px|middle|link=]]</span> this turn.",
        rarity: "rare",
    },
    {
        id: "POTION.LUCKY_TONIC",
        name: "Lucky Tonic",
        character: "any",
        description: "Gain 1 <span class=\"power-trigger inline-trigger\" data-name=\"Buffer\" data-sequel=\"2\">[[File:StS2_Icon_Buffer.png|22px|link=Slay_the_Spire_2:Buffs#Buffer]] [[Slay_the_Spire_2:Buffs#Buffer|Buffer]]</span>.",
        rarity: "rare",
    },
    {
        id: "POTION.MAZALETHS_GIFT",
        name: "Mazaleth's Gift",
        character: "any",
        description: "Gain 1 <span class=\"power-trigger inline-trigger\" data-name=\"Ritual\" data-sequel=\"2\">[[File:StS2_Icon_Ritual.png|22px|link=Slay the Spire 2:Ritual]] [[Slay the Spire 2:Ritual|Ritual]]</span>.",
        rarity: "rare",
    },
    {
        id: "POTION.OROBIC_ACID",
        name: "Orobic Acid",
        character: "any",
        description: "Add a random Attack, Skill, and Power into your Hand. They're free to play this turn.",
        rarity: "rare",
    },
    {
        id: "POTION.POISON_POTION",
        name: "Poison Potion",
        character: "silent",
        description: "Apply 6 <span class=\"power-trigger inline-trigger\" data-name=\"Poison\" data-sequel=\"2\">[[File:StS2 Icon Poison.png|22px|link=Slay the Spire 2:Poison]] [[Slay the Spire 2:Poison|Poison]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.POT_OF_GHOULS",
        name: "Pot of Ghouls",
        character: "necrobinder",
        description: "Add 2 <span class=\"card-trigger inline-trigger\" data-name=\"Soul\" data-sequel=\"2\">[[File:StS2_CardIcon_Colorless_Skill_Token.png|24px|middle|link=Slay the Spire 2:Soul]] [[Slay the Spire 2:Soul|Souls]]</span> into your Hand.",
        rarity: "rare",
    },
    {
        id: "POTION.POTION_OF_BINDING",
        name: "Potion of Binding",
        character: "any",
        description: "Apply 1 <span class=\"power-trigger inline-trigger\" data-name=\"Weak\" data-sequel=\"2\">[[File:StS2 Icon Weak.png|22px|link=Slay the Spire 2:Weak]] [[Slay the Spire 2:Weak|Weak]]</span> and 1 <span class=\"power-trigger inline-trigger\" data-name=\"Vulnerable\" data-sequel=\"2\">[[File:StS2 Icon Vulnerable.png|22px|link=Slay the Spire 2:Vulnerable]] [[Slay the Spire 2:Vulnerable|Vulnerable]]</span> to ALL enemies.",
        rarity: "uncommon",
    },
    {
        id: "POTION.POTION_OF_CAPACITY",
        name: "Potion of Capacity",
        character: "defect",
        description: "Gain 2 [[Slay the Spire 2:Orb Slots|Orb Slots]].",
        rarity: "uncommon",
    },
    {
        id: "POTION.POTION_OF_DOOM",
        name: "Potion of Doom",
        character: "necrobinder",
        description: "Apply 33 <span class=\"power-trigger inline-trigger\" data-name=\"Doom\" data-sequel=\"2\">[[File:StS2 Icon Doom.png|22px|link=Slay the Spire 2:Doom]] [[Slay the Spire 2:Doom|Doom]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.POTION_SHAPED_ROCK",
        name: "Potion-Shaped Rock",
        character: "any",
        description: "Deal 15 damage.",
        rarity: "special",
    },
    {
        id: "POTION.POWDERED_DEMISE",
        name: "Powdered Demise",
        character: "any",
        description: "Enemy loses 9 HP at the end of each of its turns.",
        rarity: "uncommon",
    },
    {
        id: "POTION.POWER_POTION",
        name: "Power Potion",
        character: "any",
        description: "Choose 1 of 3 random Power cards to add into your Hand. It's free to play this turn.",
        rarity: "common",
    },
    {
        id: "POTION.RADIANT_TINCTURE",
        name: "Radiant Tincture",
        character: "any",
        description: "Gain <span class='keyword-trigger' data-name='@CE' data-sequel='2'>[[File:StS2_EnergyColorless.png|20px|middle|link=]]</span>. Gain an additional <span class='keyword-trigger' data-name='@CE' data-sequel='2'>[[File:StS2_EnergyColorless.png|20px|middle|link=]]</span> at the start of your next 3 turns.",
        rarity: "uncommon",
    },
    {
        id: "POTION.REGEN_POTION",
        name: "Regen Potion",
        character: "any",
        description: "Gain 5 <span class=\"power-trigger inline-trigger\" data-name=\"Regen\" data-sequel=\"2\">[[File:StS2_Icon_Regen.png|22px|link=Slay_the_Spire_2:Buffs#Regen]] [[Slay_the_Spire_2:Buffs#Regen|Regen]]</span>.",
        rarity: "uncommon",
    },
    {
        id: "POTION.SHACKLING_POTION",
        name: "Shackling Potion",
        character: "any",
        description: "ALL enemies lose 7 <span class=\"power-trigger inline-trigger\" data-name=\"Strength\" data-sequel=\"2\">[[File:StS2 Icon Strength.png|22px|link=Slay the Spire 2:Strength]] [[Slay the Spire 2:Strength|Strength]]</span> this turn.",
        rarity: "rare",
    },
    {
        id: "POTION.SHIP_IN_A_BOTTLE",
        name: "Ship in a Bottle",
        character: "any",
        description: "Gain 10 <span class=\"keyword-trigger inline-trigger\" data-name=\"Block\" data-sequel=\"2\">[[File:StS2 Intent Defend.png|18px|link=Slay the Spire 2:Block]] [[Slay the Spire 2:Block|Block]]</span>. Next turn, gain 10 <span class=\"keyword-trigger inline-trigger\" data-name=\"Block\" data-sequel=\"2\">[[File:StS2 Intent Defend.png|18px|link=Slay the Spire 2:Block]] [[Slay the Spire 2:Block|Block]]</span>.",
        rarity: "rare",
    },
    {
        id: "POTION.SKILL_POTION",
        name: "Skill Potion",
        character: "any",
        description: "Choose 1 of 3 random Skill cards to add into your Hand. It's free to play this turn.",
        rarity: "common",
    },
    {
        id: "POTION.SNECKO_OIL",
        name: "Snecko Oil",
        character: "any",
        description: "Draw 7 cards. Randomize the cost of cards in your Hand this turn.",
        rarity: "rare",
    },
    {
        id: "POTION.SOLDIERS_STEW",
        name: "Soldier's Stew",
        character: "ironclad",
        description: "All cards containing [[Slay the Spire 2:Strike|Strike]] gain 1 <span class=\"keyword-trigger inline-trigger\" data-name=\"Replay\" data-sequel=\"2\">[[Slay the Spire 2:Replay|Replay]]</span> this combat.",
        rarity: "rare",
    },
    {
        id: "POTION.SPEED_POTION",
        name: "Speed Potion",
        character: "any",
        description: "Gain 5 <span class=\"power-trigger inline-trigger\" data-name=\"Dexterity\" data-sequel=\"2\">[[File:StS2 Icon Dexterity.png|22px|link=Slay the Spire 2:Dexterity]] [[Slay the Spire 2:Dexterity|Dexterity]]</span>. At the end of your turn, lose 5 <span class=\"power-trigger inline-trigger\" data-name=\"Dexterity\" data-sequel=\"2\">[[File:StS2 Icon Dexterity.png|22px|link=Slay the Spire 2:Dexterity]] [[Slay the Spire 2:Dexterity|Dexterity]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.STABLE_SERUM",
        name: "Stable Serum",
        character: "any",
        description: "<span class=\"keyword-trigger inline-trigger\" data-name=\"Retain\" data-sequel=\"2\">[[Slay the Spire 2:Retain|Retain]]</span> your Hand for 2 turns.",
        rarity: "uncommon",
    },
    {
        id: "POTION.STAR_POTION",
        name: "Star Potion",
        character: "regent",
        description: "Gain <span class='keyword-trigger' data-name='@ST' data-sequel='2'>[[File:StS2_StarRegent.png|24px|middle|link=]]</span><span class='keyword-trigger' data-name='@ST' data-sequel='2'>[[File:StS2_StarRegent.png|24px|middle|link=]]</span><span class='keyword-trigger' data-name='@ST' data-sequel='2'>[[File:StS2_StarRegent.png|24px|middle|link=]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.STRENGTH_POTION",
        name: "Strength Potion",
        character: "any",
        description: "Gain 2 <span class=\"power-trigger inline-trigger\" data-name=\"Strength\" data-sequel=\"2\">[[File:StS2 Icon Strength.png|22px|link=Slay the Spire 2:Strength]] [[Slay the Spire 2:Strength|Strength]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.SWIFT_POTION",
        name: "Swift Potion",
        character: "any",
        description: "Draw 3 cards.",
        rarity: "common",
    },
    {
        id: "POTION.TOUCH_OF_INSANITY",
        name: "Touch of Insanity",
        character: "any",
        description: "Choose a card in your Hand. It is free to play this combat.",
        rarity: "uncommon",
    },
    {
        id: "POTION.VULNERABLE_POTION",
        name: "Vulnerable Potion",
        character: "any",
        description: "Apply 3 <span class=\"power-trigger inline-trigger\" data-name=\"Vulnerable\" data-sequel=\"2\">[[File:StS2 Icon Vulnerable.png|22px|link=Slay the Spire 2:Vulnerable]] [[Slay the Spire 2:Vulnerable|Vulnerable]]</span>.",
        rarity: "common",
    },
    {
        id: "POTION.WEAK_POTION",
        name: "Weak Potion",
        character: "any",
        description: "Apply 3 <span class=\"power-trigger inline-trigger\" data-name=\"Weak\" data-sequel=\"2\">[[File:StS2 Icon Weak.png|22px|link=Slay the Spire 2:Weak]] [[Slay the Spire 2:Weak|Weak]]</span>.",
        rarity: "common",
    },
];